KISSY.add("tc/core/monitor",function(c,g,f){var e={};c.mix(e,{init:function(a){var b=this;c.mix(b.config,a);if(b.config.api){b.timer.cancel();b.timer=c.later(function(){b.send()},b.config.interval,true);g.on(window,"unload",function(){b.send(true)});b.started=true}else console.warn("[monitor]: please use your custom api.")},config:{pageId:"",interval:1E3,max:100},started:false,cache:{},__cache:{},statCache:[],toBeSend:{},timer:c.later(function(){},0),start:function(a){if(a){this.__cache[a]=this.__cache[a]||
[];this.cache[a]=this.cache[a]||[];this.__cache[a].push({start:new Date})}},end:function(a){if(a in this.cache){var b=this.__cache[a][this.__cache[a].length-1];c.mix(b,{end:new Date});this.cache[a].push(b.end-b.start);this.send()}},getBaseInfo:function(){this.toBeSend.pageId=this.config.pageId;var a=[f.core,f.shell,f[f.shell]];if(f.core==="trident"&&a.shell!="ie"){a.push("ie",f.ie);document.documentMode&&a.push(document.documentMode)}this.toBeSend.ua=a.join(",");this.toBeSend.os=this.getOSInfo();
this.toBeSend.version=c.TC.Version},getOSInfo:function(){for(var a=[["Windows NT 5.1","WinXP"],["Windows NT 6.0","WinVista"],["Windows NT 6.1","Win7"],["Windows NT 5.2","Win2003"],["Windows NT 5.0","Win2000"],["Macintosh","Macintosh"],["Windows","WinOther"],["Ubuntu","Ubuntu"],["Linux","Linux"]],b=navigator.userAgent,d=0,j=a.length;d<j;++d)if(b.indexOf(a[d][0])!=-1)return a[d][1];return"Other"},__send:function(){if(!c.isEmptyObject(this.toBeSend)){var a=[],b=this.config.api||"";this.getBaseInfo();
c.each(this.toBeSend,function(d,j){a.push(j+"="+d)});b+=(b.indexOf("?")===-1?"?":"&")+a.join("&");this.statCache.push(new Image);this.statCache[this.statCache.length-1].src=b;console.log("[monitor]: sent a monitor request:");console.log("[monitor]: %s",b)}},send:function(a){if(this.started){var b=0,d=0,j=0,i=[],k=this;c.each(k.cache,function(){b++});c.each(k.cache,function(l,n){d++;j+=k.cache[n].length;i.push(n);if(a&&b===d||j>k.config.max){c.each(i,function(m){if(k.cache[m].length!==0)k.toBeSend[m]=
k.cache[m].join(",");k.clear(m)});k.__send();k.send(a)}})}},clear:function(a){if(a)delete this.cache[a];else this.cache={}}});console.on("log",function(a){this.decorate(a.args,"monitor","color: #0c2d75")});return e},{requires:["event","ua"]});
KISSY.add("tc/core/rule",function(c,g,f,e,a){var b={groups:["global"],parents:[]},d={},j=function(){return 0},i=function(l,n,m){var h=this,r=[],p=[];h.name=c.isString(l)?l:"";h.calc=n;h.id=c.guid();h.__cache=[];h.__parents={};m=c.merge(m,{vars:[c.merge({},m&&m.vars)]});c.each(m.groups||p,function(o){o&&p.push(o)});m.groups=p.length===0?b.groups:p;c.mix(h,c.merge(b,m));for(l=h.parents.length;l>0;l--){h.vars.unshift(0);h.__parents[h.parents[l]]={}}c.each(h.groups,function(o){if(o){r.push(o+"/update");
if(d[o]===a)d[o]=[];d[o].push(h)}});i.on(r.join(" "),function(o){k.call(h,o)});h.detach("done").on("done",function(){if(h.__cache[1]!==h.result){h.result=h.__cache[1];c.each(h.groups,function(o){i.fire(o+"/update",{target:h,result:h.result})})}h.fire("selfUpdate",{result:h.result})})};c.augment(i,c.EventTarget,{result:0,update:function(l,n){if(c.isFunction(l)){n=l;l={}}c.mix(this.vars[this.vars.length-1],l);if(this.__cache[0]!==this.vars||this.__cache[1]===a)this.__cache[1]=this.calc.apply(this,this.vars)||
0;n&&this.detach("selfUpdate").on("selfUpdate",function(m){n(m.result)});this.fire("done",l);return this}});var k=function(l){if(c.inArray(l.target.name,this.parents))if(l.target!==this){console.log("[rule]: %s(%s) => %s. |%s|",l.target.name,l.result,this.name,l.type.replace("/update",""));this.__parents[l.target.name]=this.__parents[l.target.name]||{};this.__parents[l.target.name][l.target.id]=l.result;var n=this.fire("parentUpdate",{name:l.target.name,parent:this.__parents[l.target.name]})||l.result;
this.vars[c.indexOf(l.target.name,this.parents)]=n;this.update()}};c.mix(i,c.EventTarget);i.add=function(l,n,m){console.log("[rule add]: %s | %s",l,m.groups.join(","));return new i(l,n||j,m)};i.groups=d;i.sum=function(l){var n=0,m;for(m in l)n+=l[m];return n};i.cache={};return i},{requires:["event","tc/core/monitor"]});
KISSY.add("tc/mods/promotions/promotion",function(c,g,f,e){var a={promos:{},orders:{},relation:{}},b={cross:"cross_id"},d=window.blacklist=[],j={},i=function(h,r){var p;if(c.isString(h)){p=h;h=a.orders[p];if(c.isObject(h)){k();console.log("[promo]: Updating Order: %s",p);(p=h.bundle)&&c.each(p.split(";"),function(q){var t=h.sellerId;if(d[t]&&c.inArray(q,d[t])){q=c.indexOf(q,d[t]);d[t].splice(q,1)}});h.bundle=r||null;c.each(h.bundles[p]&&h.bundles[p].promos,function(q){q=q;if(c.isString(q))q=a.promos[q];
if(c.isObject(q))if(q.once){var t=q.used.pop();t?q.unused.push(t):console.log("[promo]: Not Use this Promotion")}else q.used.pop();else console.error("[promo]: Invalid Object")});h.couple=[];var o=[];h.bundles[h.bundle]&&c.each(h.bundles[h.bundle].promos,function(q){h.couple.push(l(q));a.promos[q]&&a.promos[q].once&&a.promos[q].unused.length===0&&o.push(q)});h.parent&&o.length&&c.each(a.relation[h.parent],function(q){n(a.orders[q],o,r)})}else console.error("[promo]: Invalid Order Object: ",h)}else console.error("[promo]: Invalid OrderName(String): %s",
h)},k=function(){c.each(a.promos,function(h){h.unused=h.unused||[];h.used=h.used||[]});c.each(a.orders,function(h){h.couple=h.couple||[];h.bundles=h.bundles||{};if(c.isEmptyObject(h.bundles))h.bundle=null;if(!("isBundleItem"in h))h.isBundleItem=false;if(!h.cross&&!h.parent)h.parent=b.cross});a.orders[b.cross]=a.orders[b.cross]||{}},l=function(h){if(c.isString(h))h=a.promos[h];if(c.isObject(h)){if(h.once){var r=h.unused.pop();r?h.used.push(r):console.warn("[promo]: Not Enough Promotion")}else h.used.push(h.unused[0]);
return h.used[h.used.length-1]}else console.error("[promo]: Invalid Object")},n=function(h,r){if(h.sellerId){d[h.sellerId]=d[h.sellerId]||[];c.each(h.bundles,function(p){c.each(p.promos,function(o){c.inArray(o,r)&&!c.inArray(o,d[h.sellerId])&&d[h.sellerId].push(o)})})}},m={};return c.merge({_init:function(){c.mix(j,this.config.config);c.mix(a,this.config.data);c.mix(b,this.config.meta)},merge:function(h){h.promos&&c.mix(a.promos,h.promos,false);if(h.orders)c.isEmptyObject(a.orders)?c.mix(a.orders,
h.orders):c.each(h.orders,function(r,p){c.mix(a.orders[p],r,true,["bundles","averageSum","divisionCode"]);for(var o in a.orders[p].bundles){var q=o.split(";");c.each(q,function(t){if(!a.promos[t]){console.warn("delete: %s",o);delete a.orders[p].bundles[o]}})}r.bundle&&i(p,r.bundle)});h.relation&&c.mix(a.relation,h.relation);k()},resetAll:function(){c.each(a.orders,function(h,r){if(!c.isEmptyObject(h.bundles)){m[r]=m[r]||{};m[r].bundles=c.clone(h.bundles);m[r].bundle=h.bundle;h.bundles={};h.bundle=
null;i(r,h.bundle)}})},updateOrder:i,updateAmount:function(h,r){var p=a.orders[h];if(p&&r)p.amount=r},data:a,blacklist:d,tempOrders:m,config:j,meta:b,base:function(h){return function(r){var p=this;p.groups=r;p.disabled=false;p.rule=new e(h||"promotion",function(o){if(p.disabled)return 0;return-parseInt(o.discount,10)/100},{vars:{discount:0},groups:p.groups})}},getCouples:function(h){return c.isEmptyObject(a.orders)?"":a.orders[h].couple.join(";")},getDiscount:function(h,r){var p=a.orders[h];if(!p)return 0;
r&&i(h,r);return p.bundle in p.bundles?p.bundles[p.bundle].discount:0},getDesc:function(h){if(c.isEmptyObject(a.orders)||!a.orders[h]||!a.orders[h].bundle)return"";else{h=a.orders[h];return h.bundles[h.bundle].desc}},getGift:function(h){if(c.isEmptyObject(a.orders)||!a.orders[h]||!a.orders[h].bundle)return"";else{h=a.orders[h];return h.bundles[h.bundle].gift}},getBundles:function(h){h=a.orders[h];if(!(h.sellerId in d))return h.bundles;var r=[],p=h.bundle?h.bundle.split(";"):[];c.each(d[h.sellerId],
function(u){c.inArray(u,p)||r.push(u)});var o={},q;for(q in h.bundles){var t=q.split(";"),s=true;c.each(t,function(u){if(c.inArray(u,r))s=false});if(s)o[q]=h.bundles[q]}return o}},c.EventTarget)},{requires:["ajax","json","tc/core/rule"]});
KISSY.add("tc/mods/promotions/vir-ui",function(c,g,f,e,a,b,d){var j=a('<select name="{{name}}">{{#if bundles && !KISSY.isEmptyObject(bundles)}}<option value="0">无优惠</option>{{/if}}{{#each bundles}}<option {{#if bundle==_ks_index}} selected{{/if}} bundle-data="{{_ks_index}}" value="{{(typeof couple == \'undefined\' ? []: couple).join(\'; \')}}">{{_ks_value.title}}</option>{{/each}}</select>{{#if bundles && !KISSY.isEmptyObject(bundles) && bundles[bundle] && !KISSY.isEmptyObject(bundles[bundle])}}{{bundles[bundle].gift}}{{/if}}').render;return{_init:function(){c.mix(this,
this.config);var i=g.get(this.itemPromo||"#J_ItemPromo"),k=g.get(this.shopPromo||"#J_ShopPromo"),l=g.get(this.promo||"#J_promote"),n=this.orderId;if(i){this.api||console.warn("[promo/vir-ui]: specfic promotion api needed.");if(this.promodata){var m=new e({api:this.api,from:this.from,groups:this.groups});try{m.data=c.isObject(this.promodata)?this.promodata:b.parse(this.promodata)}catch(h){console.log("[promo/vir-ui]: promoData error");return}console.log("[promo/vir-ui]: !!"+b.stringify(m.data));this.listen("quantity-change",
function(o){d.start("promotion_update_from_quantity");if(!m.data||!m.data.orders||!m.data.orders[n])console.log("[promo/vir-ui]: has no orders");else{m.data.orders[n].amount=o.quantity;m.config.type="changeamount";p()}},this.groups);var r={render:function(o){if(o)return m.isEmptyProperty(o,"bundles")?"无优惠":j(o);else{console.log("[promo/vir-ui]: no promo");return null}},initItemPromo:function(o){try{var q=this.render(c.merge(o.orders[n],{name:"bundleList_"+n}));if(q){g.html(i,"使用宝贝优惠："+q);g.show(l);
f.on(g.get("select",i),"change",function(s){m.config.type="changebundle";s=g.attr(s.target.options[s.target.selectedIndex],"bundle-data");m.updateOrder(n,s?s:null);m.update(function(u){r.initItemPromo(u);r.initShopPromo(u)},n)})}}catch(t){console.warn(t)}},initShopPromo:function(o){try{var q=this.render(o.orders[n]?c.merge(o.orders[o.orders[n].parent],{name:"bundleList_"+(o.orders[n]?o.orders[n].parent:"null")}):null);if(q){g.html(k,"使用店铺优惠："+q);g.show(l);f.on(g.get("select",k),"change",function(s){m.config.type=
"changebundle";var u=m.data.orders[n].parent;s=g.attr(s.target.options[s.target.selectedIndex],"bundle-data");m.updateOrder(u,s?s:null);m.update(function(v){console.log(v);r.initShopPromo(v)},u)})}}catch(t){console.warn(t)}}},p=function(){d.start("promotion_update");m.update(function(o){var q=m.data.orders[n];m.updateOrder(n,q.bundle);q.parent&&m.updateOrder(q.parent,m.data.orders[q.parent].bundle,true);r.initItemPromo(o);r.initShopPromo(o);d.end("promotion_update");d.end("promotion_update_from_quantity")},
n)};r.initItemPromo(m.data);r.initShopPromo(m.data)}else{g.hide(l);console.log("[promo/vir-ui]: has no promoData")}}else console.log("[promo/vir-ui]: has no itemPromo")}}},{requires:["dom","event","./promotion","template","json","tc/core/monitor"]});
KISSY.add("tc/core/common",function(c,g){if(!Number.prototype.toFixed)Number.prototype.toFixed=function(e){var a=Math.pow(10,e||0);a=String(Math.round(this*a)/a);var b=a.split(".")[1],d=0;if(b)d=b.length;else if(e!=d)a+=".";for(b=0;b<e-d;b++)a+="0";return a};var f=function(e,a){if(e)a?c.all(".label-error",e).each(function(b){b.html()==a&&b.hide()}):g.hide(g.query(".label-error",e))};return{block:function(e,a){var b=/^function\b\s*([\$\S]*)\s*\(/,d=/[^{]*\{([\d\D]*)\}$/,j=/[^\(]*\(([^\)]*)\)[\d\D]*/;
a=(a||"body").toLowerCase();e=e.toString();return a=="body"?e.replace(d,"$1").replace(/^\s*|\s*$/g,""):a=="param"?(a=e.replace(j,"$1"))?a.split(/[,\s]+/):[]:a=="name"?e.match(b)[1]:a=="anonymous"?Function.apply(this,arguments.callee(e,"param").concat(arguments.callee(e,"body"))):"Block() with bad arguments."},parseBoolean:function(e){return e&&e!="false"},error:function(e,a){f(e);if(e=g.get(e)){var b=g.get(".label-error",e)||function(){var d=document.createElement("div");g.addClass(d,"label-error");
e.appendChild(d);return d}();g.show(b);g.html(b,a||"")}},clearErr:f}},{requires:["dom"]});
KISSY.add("tc/core/form",function(c){var g={},f=c.mix(c.EventTarget,{validate:function(){if(this.stop)return true;for(var a=[].slice.call(arguments),b=true,d=0,j=this.name.length;d<j;d++)if(this.name[d]in g){b=g[this.name[d]].validate.apply(this,a);if(!b)break}if(this.name.length==1)d=0;a=b?"success":"error";console.log("[form]: %s validate result: %s, fired: %s.",this.name.join(","),b,a);this.fire(a,g[this.name[d]]);return b},stop:false,bind:function(){var a=[].slice.call(arguments),b=[],d=this,
j={events:"blur",stopAtFirst:false,haltAtFirst:true,onBeforeValidate:function(){},onValidated:function(){}},i,k=j.haltAtFirst;if(c.isPlainObject(a[a.length-1]))j=c.merge(j,a.pop());if(c.isFunction(a[a.length-1]))i=a.pop();d.stop=j.stopAtFirst;c.Event.on(a,j.events,function(l){i&&i.apply(d,a);j.onBeforeValidate.apply(d,a);c.each(a,function(m,h){b[h]=m.value});var n=d.validate.apply(d,b);d.stop=false;j.onValidated.call(d,n,l);!n&&k&&l.halt(true);return n})}}),e={};e.add=function(a,b,d,j){g[a]={validate:b||
function(){return true},msg:d||""};b=function(i){this.config={};c.isObject(i)&&c.mix(this.config,i)};d={name:c.isArray(a)?a:a.split(/[,\s]+/),mixWith:function(){for(var i=[],k,l=[].slice.call(arguments),n=0,m=l.length;n<m;n++){k=l[n];if(c.isFunction(k))i=(new k).name;if(c.isString(k)&&!c.inArray(a,this.name))i=c.isArray(a)?a:a.split(/[,\s]+/);k=0;for(var h=i.length;k<h;k++)this.name.push(i[k])}return this}};return c.augment(c.isFunction(j)&&j||b,d,f)};console.on("log",function(a){this.decorate(a.args,
"form","background: #d5ffc4")});return e});KISSY.add("tc/form/point",function(c,g){return g.add("point",function(f){f||(f=0);return/^\d+$/.test(f)&&f>=0},"使用商城积分点数必须为大于0的整数")},{requires:["tc/core/form"]});KISSY.add("tc/form/compareNum",function(c,g){return g.add("compareNum",function(f,e){f||(f=0);return parseInt(f)<=(e===Infinity?e:parseInt(e))},"您使用的商城积分点数超过了该次订单确认允许使用的最大商城积分点数")},{requires:["tc/core/form"]});
KISSY.add("tc/mods/point/point",function(c,g,f,e){var a={};a.validates={point:new g,maxUse:new f};a._init=function(){var b=c.mix(this,this.config);b.rule=e.add("point",function(d){return-d.point},{groups:this.groups});b.maxUseRule=e.add("maxUsePoint",function(d){return d*100},{parents:["b2cShopTotal"],groups:b.groups});b.maxUseRule.on("parentUpdate",function(d){if(d.name==="b2cShopTotal")return e.sum(d.parent)});b.maxUseRule.on("selfUpdate",function(d){console.log("[maxUsePoint]: "+d.result);b.maxUse=
d.result>b.point?b.point:d.result;b.maxUseRule.fire("selfUpdateComplete")});b.validates.point.on("error",function(){b.rule.update({point:0})});b.validates.maxUse.on("error",function(){b.rule.update({point:0})})};a.test=function(){return this.validates.point.validate(this.usePoint)&&this.validates.maxUse.validate(this.usePoint,this.maxUse)};a.change=function(b){b=c.mix(this,b);var d=b.test();d&&b.rule.update({point:b.usePoint/100});return d};return a},{requires:["tc/form/point","tc/form/compareNum",
"tc/core/rule"]});
KISSY.add("tc/mods/point/ui",function(c,g,f,e,a){return{_init:function(){var b=c.mix(this,this.config);b.logic=new a({point:parseInt(b.pointEl.innerHTML||"0",10),usePoint:c.trim(b.useEl.value||0),maxUse:0,groups:b.groups});var d=c.get("div.msg",b.useEl.parentNode);b.logic.validates.point.on("error",function(j){c.get("p",d).innerHTML=j.msg;g.show(d);b.priceEl.innerHTML="-0.00"}).on("success",function(){g.hide(d)});b.logic.validates.maxUse.on("error",function(j){c.get("p",d).innerHTML=j.msg;g.show(d)}).on("success",
function(){g.hide(d)});b.logic.maxUseRule.on("selfUpdateComplete",function(){b.renderData();b.bindEvents()})},renderData:function(){this.maxPriceEl.innerHTML=(this.logic.maxUse/100).toFixed(2);this.maxUseEl.innerHTML=this.logic.maxUse.toFixed(0);var b=this.logic.usePoint/100;b=isNaN(b)?0:b;this.priceEl.innerHTML="-"+b.toFixed(2)},bindEvents:function(){var b=this;f.on(b.useEl,"keyup",b.pointChangeHandler,b);b.listen("toggle-point",function(d){d=!!d.disable;g[d?"addClass":"removeClass"](b.useEl,"input-disabled");
g.attr(b.useEl,"disabled",d);g.attr(b.useEl,"readonly",d);if(d){b.useEl.value=0;b.pointChangeHandler()}},["global"]);b.listen("global-test",function(){return b.logic.test()},["global"]);b.bindEvents=function(){}},pointChangeHandler:function(){if(this.logic.change({usePoint:c.trim(this.useEl.value||0)}))this.renderData()}}},{requires:["dom","event","tc/core/common","tc/mods/point/point"]});
KISSY.add("tc/mods/winPoints/showWinPoints",function(c,g){var f={};f._init=function(){var e=c.mix(this,this.config);e.rule=g.add("cartWinPoint",function(a){return a},{parents:["shopWinPoint"],groups:e.groups});e.rule.on("parentUpdate",function(a){if(a.name==="shopWinPoint")return g.sum(a.parent)})};return f},{requires:["tc/core/rule"]});
KISSY.add("tc/mods/winPoints/showWinPoint-ui",function(c,g,f){g={};g._init=function(){var e=c.mix(this,this.config);e.logic=new f({groups:e.groups});e.logic.rule.on("selfUpdate",function(a){e.winPointEl.innerHTML=a.result})};return g},{requires:["dom","tc/mods/winPoints/showWinPoints"]});
KISSY.add("tc/mods/winPoints/winPoints",function(c,g){var f={};f._init=function(){var e=c.mix(this,this.config);e.rule=g.add("shopWinPoint",function(a,b){return a+ +b.giftPoint},{parents:["itemWinPoint"],groups:e.groups,vars:{giftPoint:0}});e.rule.on("parentUpdate",function(a){if(a.name==="itemWinPoint")return g.sum(a.parent)})};return f},{requires:["tc/core/rule"]});
KISSY.add("tc/mods/winPoints/winPoint-ui",function(c,g,f,e){return{_init:function(){var a=c.mix(this,this.config);a.logic=new e({groups:a.groups})},updatePoint:function(a){this.logic.rule.update({giftPoint:a})}}},{requires:["dom","event","tc/mods/winPoints/winPoints"]});
KISSY.add("tc/form/birth",function(c,g){return g.add("birth",function(f){var e;if(e=f.length>=18)a:{var a=f.substring(6,14);f=parseInt(a.substring(0,4),10);e=parseInt(a.substring(4,6),10);a=parseInt(a.substring(6,8),10);var b=[31,28,31,30,31,30,31,31,30,31,30,31];if(f>=1900&&f<2010&&b[e-1])if(e==2&&f/4==0&&f!=1900&&a>0&&a<=29){e=true;break a}else if(a>0&&a<=b[e-1]){e=true;break a}e=false}return e})},{requires:["tc/core/form"]});
KISSY.add("tc/form/id",function(c,g){return g.add("id",function(f){return f.match(/^(([0-9]{0,18})|([0-9]{17,17}x))$/i)})},{requires:["tc/core/form"]});KISSY.add("tc/form/notNull",function(c,g){return g.add("notNull",function(f){return!!c.trim(f)},"不能为空")},{requires:["tc/core/form"]});
KISSY.add("tc/form/18",function(c,g){return g.add("18",function(f){var e=new Date,a=e.getMonth()+1+"",b=e.getDate()+"";a=a.length<2?"0"+a:""+a;b=b.length<2?"0"+b:""+b;e=parseInt(e.getFullYear()-18+a+b);return parseInt(f.substring(6,14),10)<=e})},{requires:["tc/core/form"]});
KISSY.add("tc/mods/authentication/logic",function(c,g,f,e,a){var b={},d={birth:new g,id:new f,notNull:new e,largeThan18:new a},j={birth:"身份证号码有误，请重新输入",notNull:"请输入身份证号码",largeThan18:"您还未满18岁，不能进行网游类商品交易"};c.mix(b,{testId:function(i,k,l){c.each(["birth","notNull","largeThan18"],function(n){if(d[n].validate(i)){this.hasError=false;l&&l()}else{k&&k(j[n]);this.hasError=true;return false}},this)},testBirth:function(i){return d.birth.validate(i)},validateId:function(i){return d.id.validate(i)},adjustId:function(i){if(i.length<
18)i=i.replace(/[^0-9]/g,"");else if(i.length==18)i=i.replace(/[^0-9xX]/g,"");return i},testCharOnSubmit:function(i){this.hasError=false;if(i.length==18)if(/\d{17}[^0-9xX]/.test(i)){i=i.substring(0,17);this.hasError=true}else{if(/\D/g.test(i.substring(0,17))){i=i.replace(/[^0-9]/g,"");this.hasError=true}}else if(/[^0-9]/g.test(i)){i=i.replace(/[^0-9]/g,"");this.hasError=true}else this.hasError=false;return i}});return b},{requires:["tc/form/birth","tc/form/id","tc/form/notNull","tc/form/18"]});
KISSY.add("tc/mods/authentication/ui",function(c,g,f,e,a){g={};c.mix(g,{show:function(){this.popup.center();this.popup.show()},hide:function(){this.popup.hide()},_init:function(){if(f.get("#J_PopupIdConfirm")){var b=this;KISSY.use("overlay",function(d,j){b.logic=new a;b.shadow=f.get("#J_shadow");b.input=f.get("#J_InputIdConfirm");b.error=f.get("#J_ErrorIdConfirm");b.popup=new j({srcNode:"#J_PopupIdConfirm",zIndex:19999,mask:true});d.one("#J_PopupIdConfirm").removeClass("hidden");b.show();d.one(".ks-ext-mask").addClass("shadow");
b.popup.on("beforeVisibleChange",function(i){if(!i.newVal)if(f.get("#J_RadioOther").checked)b.input.value||b.showError("请输入身份证号码");else{b.testCharOnSubmit();b.testId();if(b.logic.hasError)return false}});e.on(b.input,"blur",b.testId,b);e.on(b.input,"keyup",b.testChar,b);f.get("#J_RadioInland").checked="checked";e.on(f.get("#J_RadioOther"),"click",b.radioOtherFocus,b);e.on(f.get("#J_ButtonIdConfirm"),"click",b.onSubmit,b)})}},showError:function(b){var d=this.error;f.css(d,"visibility","visible");d.innerHTML=
b},clearError:function(){f.css(this.error,"visibility","hidden")},testId:function(){var b=this;b.logic.testId(b.input.value,function(d){b.showError(d)},function(){b.clearError()})},testChar:function(){var b;b=false;var d;d=this.input;if(b=!this.logic.validateId(d.value)){if(document.selection){b=document.selection.createRange().duplicate();b.moveEnd("character",this.input.value.length);b=this.input.value.lastIndexOf(b.text)}else b=this.input.selectionStart;d.value=this.logic.adjustId(d.value);if(document.selection){d=
this.input.createTextRange();d.collapse(true);d.move("character",b-1);d.select()}else{this.input.selectionStart=b-1;this.input.selectionEnd=b-1}}},testCharOnSubmit:function(){var b=this.input;b.value=this.logic.testCharOnSubmit(b.value)},radioOtherBlur:function(){e.remove(f.get("#J_RadioInland"),"click",this.radioOtherBlur,this);f.get("#confirmIdTipSpan").style.visibility="visible";f.html(f.get("#confirmIdLabel"),"身份证号码：");this.clearAll();this.logic.hasError=true;e.remove(f.get("#J_RadioInland"),
"click",this.radioOtherBlur,this);e.remove(this.input,"blur",this.onEasyBlur,this);e.remove(f.get("#J_ButtonIdConfirm"),"click",this.onEasySubmit,this);e.on(this.input,"blur",this.testId,this);e.on(this.input,"keyup",this.testChar,this);e.on(f.get("#J_ButtonIdConfirm"),"click",this.onSubmit,this);e.on(f.get("#J_RadioOther"),"click",this.radioOtherFocus,this)},radioOtherFocus:function(){f.get("#confirmIdTipSpan").style.visibility="hidden";f.html(f.get("#confirmIdLabel"),"身份證號碼：");this.clearAll();this.logic.hasError=
true;e.remove(f.get("#J_RadioOther"),"click",this.radioOtherFocus,this);e.remove(this.input,"blur",this.testId,this);e.remove(this.input,"keyup",this.testChar,this);e.remove(f.get("#J_ButtonIdConfirm"),"click",this.onSubmit,this);e.on(f.get("#J_ButtonIdConfirm"),"click",this.onEasySubmit,this);e.on(f.get("#J_RadioInland"),"click",this.radioOtherBlur,this);e.on(this.input,"blur",this.onEasyBlur,this)},onSubmit:function(){this.testCharOnSubmit();this.testId();if(this.logic.hasError)return false;else this.hide()},
onEasySubmit:function(){if(this.input.value){this.clearError();this.hide()}else{this.showError("请输入身份证号码");return false}},onEasyBlur:function(){this.input.value||this.showError("请输入身份证号码")},clearAll:function(){this.clearError();this.input.value=""}});return g},{requires:["ua","dom","event","./logic"]});
KISSY.add("tc/mods/warning-popup/ui",function(c){return{_init:function(){c.one("#J_popup")&&KISSY.use("overlay",function(g,f){g.one("#J_popup").removeClass("hidden").css("padding","25px");var e=new f({srcNode:"#J_popup",zIndex:2E4,mask:true});e.center();e.show();g.one(".ks-ext-mask").addClass("shadow");var a=g.one("#J_popup .J_closeBtn"),b=a.html();a.attr("disabled",true);a.on("click",function(){e.hide()});e.on("beforeVisibleChange",function(j){if(!j.newVal&&a.attr("disabled"))return false});KISSY.Event.on(window,
"resize",function(){e.center()});for(var d=0;d<6;d++)(function(j){setTimeout(function(){if(j==5){a.attr("disabled",false);a.html(b)}else a.html("("+(5-j)+") "+b)},j*1E3)})(d)})}}});KISSY.add("tc/mods/itemInfo/item",function(c,g){var f={};f._init=function(){var e=c.mix(this,this.config);e.rule=g.add("itemPrice",function(a){return a.price},{vars:{price:e.price},groups:[e.groups]});e.rule.update()};return f},{requires:["tc/core/rule"]});
KISSY.add("tc/mods/itemInfo/ui",function(c,g){var f={};f._init=function(){this.logic=new g(this.config)};return f},{requires:["./item"]});KISSY.add("tc/form/number",function(c,g){return g.add("number",function(f,e){return/^\d+$/.test(f)&&+f>0&&+f<(e||Number.MAX_VALUE)},"购买数量必须为大于0的整数")},{requires:["tc/core/form"]});
KISSY.add("tc/mods/quantity/quantity",function(c,g,f,e,a){var b={};b._init=function(){var d=this;d.validates={quantityNum:new f,quantityCompare:new e};d.setData(d.config);d.rule=g.add("quantity",function(j,i){return j*i.quantity},{parents:["itemPrice"],groups:d.groups,vars:{quantity:d.quantity}});d.rule.on("selfUpdate",function(){d.fire("change",{quantity:d.quantity});d.broadcast("quantity-change",{quantity:d.quantity})});d.listen("global-test",function(){return d.test()});d.rule.update()};b.setData=
function(d){c.mix(this,d,true)};b.test=function(){return this.maxQuantity===a||this.maxQuantity===""?this.validates.quantityNum.validate(this.quantity):this.validates.quantityNum.validate(this.quantity)&&this.validates.quantityCompare.validate(this.quantity,this.maxQuantity)};b.change=function(d){this.setData(d);if(this.test()){console.log("[quantity]: Updating quantity: %s",this.quantity);this.rule.update({quantity:this.quantity});return true}return false};return b},{requires:["tc/core/rule","tc/form/number",
"tc/form/compareNum"]});
KISSY.add("tc/mods/quantity/normal-ui",function(c,g,f,e,a){var b={};b._init=function(){c.mix(this,this.config);var d=g.get(this.quantity||"#J_Quantity"),j=g.get(this.allowQuantity||"#J_AllowQuantity"),i=c.trim(this.maxValue||g.attr(j,"allowquantity"));j={type:"normal",quantity:c.trim(d.value),maxQuantity:i,groupId:this.groupId,fullPointPay:this.fullPointPay||false};var k=new e(j);j=k.validates;j.quantityNum.on("error",function(l){a.error(d.parentNode,l.msg)}).on("success",function(l){a.clearErr(d.parentNode,
l.msg)});j.quantityCompare.on("error",function(){a.error(d.parentNode,"最多只能购买"+i+"件")}).on("success",function(){a.clearErr(d.parentNode,"最多只能购买"+i+"件")});f.on(d,"keyup",function(){k.change({quantity:c.trim(d.value)})})};return b},{requires:["dom","event","./quantity","tc/core/common"]});KISSY.add("tc/form/mobile",function(c,g){return g.add("mobile",function(f){return/^\d{2,11}$/.test(c.trim(f))},"请输入正确的号码，手机号码必须全为数字，且不能超过11位")},{requires:["tc/core/form"]});
KISSY.add("tc/form/length",function(c,g){var f=g.add("length",function(a,b){return a.length<=(b||100)},"不能超过100"),e=f.prototype.validate;f.prototype.validate=function(){var a=[].slice.call(arguments);if(this.config&&this.config.max)a[1]=this.config.max;return e.apply(this,a)};return f},{requires:["tc/core/form"]});KISSY.add("tc/form/repeat",function(c,g){return g.add("repeat",function(f,e){return c.trim(f)===c.trim(e)},"两次输入不一致")},{requires:["tc/core/form"]});
KISSY.add("tc/form/identityCard",function(c,g){return g.add("identityCard",function(f){return/^\d{17}[x0-9X]$|^$/.test(f)},"请输入正确的身份证号")},{requires:["tc/core/form"]});
KISSY.add("tc/mods/generQRCode/generQRCode",function(c,g,f,e,a,b){var d={mySelfMob:new g,mySelfMobRepeat:new e,friendMob:new g,friendMobRepeat:new e,nameNotNull:new b,nameLength:new f({max:9}),identityCard:new a,identityCardRepeat:new e};g={validates:d,isFriend:function(){return this.to==="friend"}};g._init=function(){c.mix(this,this.config);var j=this;this.listen("global-test",function(){return j.test()})};g.test=function(j){var i=this,k=true,l=function(){return i.isFriend()?d.friendMobRepeat.validate(i.friendMob.value,
i.friendMobRepeat.value):d.mySelfMobRepeat.validate(i.mySelfMob.value,i.mySelfMobRepeat.value)},n=function(){var q;if(i.isFriend())(q=d.friendMob.validate(i.friendMob.value))&&i.friendMobRepeat.value&&l();else(q=d.mySelfMob.validate(i.mySelfMob.value))&&i.mySelfMobRepeat.value&&l();return q},m=function(){if(!i.name){console.warn("[generQRCode]: name not found, return true.");return true}return d.nameNotNull.validate(i.name.value)&&d.nameLength.validate(i.name.value)},h=function(){if(!i.identityCard){console.warn("[generQRCode]: identityCard not found, return true.");
return true}var q=d.identityCard.validate(i.identityCard.value);q&&r();return q},r=function(){if(!i.identityCardRepeat){console.warn("[generQRCode]: identityCardRepeat not found, return true.");return true}return d.identityCardRepeat.validate(i.identityCard.value,i.identityCardRepeat.value)},p={mySelfMob:n,mySelfMobRepeat:l,friendMob:n,friendMobRepeat:l,name:m,identityCard:h,identityCardRepeat:r};if(j){for(var o in j)if(o in p)k=k&&p[o]();else console.log("xy warning:"+o+" is not in map!!   -------tc/mods/generQRCode/generQRCode");
return k}else{j=n()&&l();m=i.isFriend()?m():true;h=i.to?true:h()&&r();console.log("[all test]:"+j+" "+m+" "+h);return j&&m&&h}};g.setData=function(j){j&&c.mix(this,j)};g.change=function(j){c.mix(this,j,true);return this.test(j)};return g},{requires:["tc/form/mobile","tc/form/length","tc/form/repeat","tc/form/identityCard","tc/form/notNull"]});
KISSY.add("tc/mods/generQRCode/ui",function(c,g,f,e,a){var b={};b._init=function(){var d={friend:g.get("#J_Present .J_ToFriend"),mySelf:g.get("#J_Present .J_ToMyself"),friendUl:g.get("#J_ToFriend"),mySelfUl:g.get("#J_ToMySelf"),presentInfo:g.get("#J_PresentInfo")},j;for(j in d)if(!d[j]){console.warn("[generQRCode/ui] element %s not found. delete it.",j);delete d[j]}var i={friendMob:g.get("#J_friendMob"),friendMobRepeat:g.get("#J_SureFriendMobile"),mySelfMob:g.get("#J_MyMobile"),mySelfMobRepeat:g.get("#J_SureMyMobile"),
name:g.get("#J_Name")};for(j in i)if(!i[j]){console.warn("[generQRCode/ui] inputElement %s not found. delete it.",j);delete i[j]}var k={mySelfMob:{el:"mySelfMob"},mySelfMobRepeat:{el:"mySelfMobRepeat"},friendMob:{el:"friendMob"},friendMobRepeat:{el:"friendMobRepeat"},nameNotNull:{el:"name",msg:"姓名或昵称不能为空"},nameLength:{el:"name",msg:"最多可输入9个字"}},l=function(p){p&&c.each(g.query("input",p),function(o){if(o.id!="J_Benediction")o.value=""})};j={friendMob:{value:c.trim(i.friendMob.value)},friendMobRepeat:{value:c.trim(i.friendMobRepeat.value)},
name:{value:c.trim(i.name.value)},identityCard:{value:""},identityCardRepeat:{value:""},to:"friend",NAME_LENGTH:9};var n=new e(j),m=function(p){if(p){g.addClass(d.friendUl,"hidden");g.removeClass(d.mySelfUl,"hidden");g.addClass(d.presentInfo,"hidden");a.clearErr(d.friendUl);l(d.friendUl);n.setData({mySelfMob:{value:c.trim(i.mySelfMob.value)},mySelfMobRepeat:{value:c.trim(i.mySelfMobRepeat.value)},friendMob:{value:""},friendMobRepeat:{value:""},name:{value:""},to:"myself"})}else{g.removeClass(d.friendUl,
"hidden");g.addClass(d.mySelfUl,"hidden");g.removeClass(d.presentInfo,"hidden");a.clearErr(d.mySelfUl);l(d.mySelfUl);n.setData({mySelfMob:{value:""},mySelfMobRepeat:{value:""},friendMob:{value:c.trim(i.friendMob.value)},friendMobRepeat:{value:c.trim(i.friendMob.value)},name:{value:c.trim(i.name.value)},to:"friend"})}};d.mySelf.checked&&m(true);d.friend.checked&&m(false);var h=n.validates;j=function(p){var o=k[p].el,q=i[o];if(q){var t=k[p].msg;h[p].on("error",function(s){a.error(q.parentNode,t||s.msg)}).on("success",
function(s){a.clearErr(q.parentNode,t||s.msg)})}else console.log("tc/mods/generPhone/ui element： "+o+" not exist")};for(var r in k)j(r);c.each(i,function(p){f.on(p,"blur",function(o){var q={},t;for(t in i)if(o.target===i[t])q[t]={value:c.trim(i[t].value)};n.change(q)})});f.on("#J_Present","click",function(p){p=p.target;g.hasClass(p,"J_ToMyself")&&m(true);g.hasClass(p,"J_ToFriend")&&m(false)})};return b},{requires:["dom","event","tc/mods/generQRCode/generQRCode","tc/core/common"]});
KISSY.add("tc/mods/memo/memo",function(c,g,f){var e={memo:{readOnly:false,maxLength:500,value:"",needMemoNullTest:false}};e._init=function(){var a=this;c.mix(a.memo,a.config,true);a.validates={memoNotNull:new g,memoLength:new f({max:a.memo.maxLength})};a.listen("global-test",function(){if(a.test()){a.fire("clean-msg");return true}return false},this.groups);a.memo&&a.memo.value!==""&&a.test()};e.setData=function(a){c.mix(this,a,true)};e.change=function(a){c.mix(this,a,true);return this.test()};e.test=
function(){return this.needMemoNullTest?this.validates.memoNotNull.validate(this.memo.value)&&this.validates.memoLength.validate(this.memo.value):this.validates.memoLength.validate(this.memo.value)};return e},{requires:["tc/form/notNull","tc/form/length"]});
KISSY.add("tc/core/widget",function(c,g,f){g=c.DOM;f=c.Event;var e={};e.InputHint={decorate:function(a,b){var d=/^\s*$/;a=g.get(a);b=c.merge({hintMessage:"",hintClass:"tb-input-hint",appearOnce:false},b||{});var j=b.hintMessage||a.title||"";if(c.trim(j)){var i=g.create("<div style='position:relative;display:inline-block;*display:inline;*zoom:1;'>");g.insertBefore(i,a);i.appendChild(a);var k={};k.disabled=false;var l=(new c.Node("<div style='position:absolute;left:-9999px;top:-9999px;' class='"+b.hintClass+
"'>"+j+"</div>")).insertAfter(a);l.css("width",a.offsetWidth);k.disappear=function(){l.offset({left:-9999,top:-9999})};k.appear=function(){if(d.test(a.value)){var h=g.offset(a);h.left+=5;l.offset(h)}};k.purge=function(){this.disappear();f.remove(a,"focus",n);f.remove(a,"drop",n);f.remove(a,"blur",m)};var n=function(){a.focus();k.disabled||k.disappear()},m=function(){k.disabled||k.appear()};a.title||g.attr(a,"title",j);f.on([a,l[0]],"focus",n);f.on(a,"drop",n);b.appearOnce||f.on(a,"blur",m);setTimeout(function(){k.appear()},
0);return k}}};return e},{requires:["dom","event"]});
KISSY.add("tc/mods/memo/ui",function(c,g,f,e,a,b){g={};g._init=function(){c.mix(this,this.config);var d=c.get(this.memo||"#J_msgtosaler");if(d){var j=this.maxLength||500,i=this.groupId,k=this.needMemoNullTest||false;i={value:c.trim(d.value),maxLength:j,groupId:i,needMemoNullTest:k};var l=new e(i);b.InputHint.decorate("#"+d.id,{hintClass:"tips"});i=l.validates;i.memoLength.on("error",function(){a.error(d.parentNode,"最多输入"+j+"个字符")}).on("success",function(){a.clearErr(d.parentNode,"最多输入"+j+"个字符")});
k&&i.memoNotNull.on("error",function(){a.error(d.parentNode,"不能为空")}).on("success",function(){a.clearErr(d.parentNode,"不能为空")});f.on(d,"blur",function(){l.change({memo:{value:c.trim(d.value)}})})}else console.warn("[memo]: memo %s is not found, ignored.",this.memo)};return g},{requires:["dom","event","./memo","tc/core/common","tc/core/widget"]});
KISSY.add("tc/mods/payForAnother/payForAnother",function(c){var g={readOnly:false,isChecked:false};g._init=function(){c.mix(this,this.config,true);this.listen("postType-change fareInsure-change",function(f){f.target.postType="cod";this.fire("disabled-el")})};g.change=function(f){this.readOnly?console.log("payForAnother is read only"):c.mix(this,f)};return g});
KISSY.add("tc/mods/payForAnother/ui",function(c,g,f,e){c={};c._init=function(){var a=g.get("#find-another"),b=new e({readOnly:true,isChecked:a.checked});b.on("disabled",function(){a.disabled="disabled"});b.on("un-disabled",function(){a.disabled=""});f.on(a,"click",function(d){b.change({isChecked:d.target.checked})})};return c},{requires:["dom","event","./payForAnother"]});
KISSY.add("tc/mods/realPay/realPay",function(c,g){var f={realMoney:{readOnly:false,value:""}};f._init=function(){var e=this;c.mix(e.realMoney,e.config,true);e.rule=g.add("realPay",function(a,b){var d=a+b;if(d<0){console.log("[realpay]: result is less than zero. use 0");d=0}return d},{parents:["shopPay","point"],groups:e.groups});e.rule.on("parentUpdate",function(a){if(a.name==="shopPay")return g.sum(a.parent)});e.rule.on("selfUpdate",function(a){console.log("[realPay]: |%s| %s",e.config.cartId,a.result);
e.realMoney.fullPointPay?e.show(0):e.show(a.result)})};f.show=function(e,a){var b=(e||e===0?e:this.realMoney.value).toFixed(2);this.fire("realPay-show",c.mix({realMoney:b},a),null,this.groupId)};f.setMoney=function(e,a){if(this.realMoney.readOnly)console.log("[realpay]: realMoney is readOnly");else{this.realMoney.value=e;a&&this.show(this.realMoney.value)}};return f},{requires:["tc/core/rule"]});
KISSY.add("tc/mods/realPay/ui",function(c,g){var f={};f._init=function(){c.mix(this,this.config);var e=c.one(this.actualFee||"#J_ActualFee"),a=c.one(this.totalSum||"#J_TotalSum");(new g(this.config)).on("realPay-show",function(b){e.html(b.realMoney);a&&a.val(b.realMoney)},null,this.groups)};return f},{requires:["./realPay"]});
KISSY.add("tc/mods/submit/submit",function(c,g){return{submit:function(){var f=this;g.get("#J_verifyImage")?f.listen("checkCode:success",function(){f.test()}):f.test();f.broadcast("checkCode")},test:function(){this.broadcast("global-test")!==false&&this.fire("submit")}}},{requires:["dom","tc/core/monitor"]});
KISSY.add("tc/mods/submit/ui",function(c,g,f,e){var a={};a._init=function(){var b=c.mix(this,this.config),d=new e,j=c.get(this.submitForm||"#J_Form"),i=c.get(this.submitId||"#J_Go");i&&(i.disabled=false);d.on("submit",function(){if(i){i.disabled=true;if(b.isTips&&b.isTips.value){var k=c.get(".submit-tips");if(!k){k=document.createElement("div");g.addClass(k,"submit-tips");i.parentNode.appendChild(k);g.show(k);k.innerHTML="正在处理，请稍候..."}}}j.submit()});f.on(i,"click",function(k){k.halt(true);d.submit()});
f.on(j,"submit",function(k){k.halt(true);d.submit()})};return a},{requires:["dom","event","./submit"]});KISSY.add("tc/mods/checkCode/checkCode",function(c,g,f){g={checkCode:{value:""},validates:{checkCodeNotNull:new f}};g._init=function(){c.mix(this,this.config)};g.test=function(){return this.validates.checkCodeNotNull.validate(this.checkCode.value)};g.change=function(e){c.mix(this,e,true);return this.test(e)};return g},{requires:["tc/form/length","tc/form/notNull"]});
KISSY.add("tc/mods/checkCode/ui",function(c,g,f,e,a,b){var d={};d._init=function(){var j=c.mix(this,this.config),i=f.get(this.img||"#J_verifyImage"),k=f.get(this.checkCode||"#verify-code"),l=f.get(this.nextCode||"#J_verifyTrigger"),n=f.get("#J_checkCodeUrl");if(!k||!n)console.log("[checkcode]: checkCode is not use..");else{var m=new b({checkCode:{value:k.value}});j.checkCodeURL=n.value;j.logic=m;j.checkCodeEl=k;e.on(l,"click",function(h){h.halt();i.src=i.src+"&t="+(new Date).getTime()});m.validates.checkCodeNotNull.on("error",
function(){a.error(k.parentNode,"请填写校验码")}).on("success",function(){c.later(function(){a.clearErr(k.parentNode,"请填写校验码")},500,false)});e.on(k,"blur",function(){m.change({checkCode:{value:k.value}})});j.listen("global-test",function(){return m.change({checkCode:{value:k.value}})});j.listen("checkCode",function(){j.verifyCode()})}};d.verifyCode=function(){var j=this,i=j.checkCodeURL,k=f.get("#J_Form").elements;if(k.isCheckCode){var l=[];c.each(["isCheckCode","encrypterString","sid","gmtCreate","checkCodeIds"],
function(n){l.push(n+"="+(k[n]&&k[n].value))});i=i+(i.indexOf("?")===-1?"?":"&")+l.join("&");i+="&checkCode="+c.trim(j.logic.checkCode.value);g.get(i,function(n){if(n!=="error"){if(k.newCheckCode)k.newCheckCode.value=n;else f.create('<input type="hidden" name="newCheckCode" value="'+n+'" />');j.broadcast("checkCode:success")}else{a.error(j.checkCodeEl.parentNode,"请填写正确的校验码");n=f.get(this.img||"#J_verifyImage");n.src=n.src+"&t="+(new Date).getTime()}})}};return d},{requires:["ajax","dom","event","tc/core/common",
"tc/mods/checkCode/checkCode"]});
KISSY.add("tc/mods/totalFee/totalFee",function(c,g){var f={totalFee:{readOnly:false,value:0}};f._init=function(){var e=this;c.mix(e.totalFee,e.config,true);e.rule=g.add("totalFee",function(a,b,d){return a+b+d},{parents:["itemTotal","fareTemplate","cod"],groups:this.groups});e.rule.on("parentUpdate",function(a){if(a.name==="itemTotal")return g.sum(a.parent)});e.rule.on("selfUpdate",function(a){e.broadcast("totalFee-show",{totalFee:a.result},e.groups);e.show(a.result)})};f.show=function(e){this.fire("totalFee-show",
{totalFee:e?e.toFixed(2):this.totalFee.value.toFixed(2)})};f.setMoney=function(e,a){if(this.totalFee.readOnly)console.log("realMoney is readOnly");else{this.totalFee.value=e;a&&this.show(this.totalFee.value)}};return f},{requires:["tc/core/rule"]});
KISSY.add("tc/mods/totalFee/ui",function(c,g,f,e){f={};f._init=function(){c.mix(this,this.config);var a=g.get(this.totalPrice||"#J_TotalFee");(new e({groupId:this.groupId})).on("totalFee-show",function(b){if(a)a.innerHTML=b.totalFee})};return f},{requires:["dom","event","./totalFee"]});
KISSY.add("tc/mods/point/fullPointPay-ui",function(c,g,f){var e=c.DOM;return{_init:function(){c.mix(this,this.config);var a=e.get(this.maxUseEl||"#ark_maxUsePointValue"),b=e.get(this.maxPriceEl||"#ark_maxUsePointPriceValue"),d=e.get(this.pointEl||"#ark_pointValue");this.listen("quantity-change",function(i){console.log(i.result)});var j=new f({point:{value:parseInt(d.innerHTML||"0")},use:{value:0},maxUse:{value:0},fullPointPay:{value:true}});j.on("totalFee-ready",function(){b.innerHTML=j.getPrice(j.getMaxUsePoint()).toFixed(2);
a.innerHTML=j.getMaxUsePoint()});j.validates.maxUse.on("error",function(){g.error(d.parentNode,"对不起，您持有的商城积分点数不足以换购此商品")}).on("success",function(){g.clearErr(d.parentNode,"对不起，您持有的商城积分点数不足以换购此商品")})}}},{requires:["tc/core/common","tc/mods/point/point"]});
KISSY.add("tc/mods/totalPointPay/totalPointPay",function(c){var g={};g._init=function(){var f=this,e=this.config||{};c.mix(f,f.config,true);f.listen("quantity-change",function(a){setTimeout(function(){console.log("quantity-change is listened by totalPointPay!,realPay:"+a.result);f.broadcast("totalPointPay-show",{result:a.result*100},null,e.groupId);f.show(a.result)},0)},null,e.groupId)};g.show=function(f){this.fire("totalPointPay-show",{totalPointPay:f.toFixed(2)})};return g});
KISSY.add("tc/mods/totalPointPay/ui",function(c,g,f,e){f={};f._init=function(){c.mix(this,this.config);var a=g.get(this.totalPrice||"#J_needPoints");(new e).on("totalPointPay-show",function(b){a.innerHTML=b.totalPointPay*100})};return f},{requires:["dom","event","./totalPointPay"]});
KISSY.add("tc/cart/qrCodeOrder",function(c,g,f,e,a,b,d,j,i,k,l,n,m,h,r,p,o,q){var t={},s=c.DOM;t._init=function(){c.mix(this,this.config);var u=c.guid(),v=this.winPoint||false;this.usePoint=this.usePoint||false;this.fullPointPay=this.fullPointPay||false;new b;new d;new g({api:this.promoAPI,orderId:this.orderId,promodata:this.promodata,from:this.from||"buynow",promo:this.promo,itemPromo:this.itemPromo,shopPromo:this.shopPromo,groupId:u});if(v){this.showPoint=new e;this.winPonit=new a({rate:s.get("#J_Rate")?
s.get("#J_Rate").value:0,id:u,presentPoint:s.get("#J_PresentPoint")?s.get("#J_PresentPoint").value:0,codBias:s.get("#J_CodBias")?s.get("#J_CodBias").value:0,manjiujianBias:s.get("#J_ManjiujianBias")?s.get("#J_ManjiujianBias").value:0})}this.quantity=new i({groupId:u});this.beizhuUI=new l({memo:"#J_Benediction",maxLength:18});this.memo=new l({memo:"#J_msgtosaler"});this.payForAnother=new n;new p({totalPrice:"#ark_totalPrice",groupId:u});if(this.usePoint)if(this.fullPointPay){new o({fullPointPay:this.fullPointPay,
needPointEl:"J_needPoints"});new q}else new f({pointEl:"#ark_pointValue",useEl:"#ark_usePointId",priceEl:"#profitId",maxPriceEl:"#ark_maxUsePointPriceValue",groupId:u,maxUseEl:"#ark_maxUsePointValue"});new m({fullPointPay:this.fullPointPay,groupId:u});this.itemInfo=new j({groupId:u});this.submit=new h({isTips:{value:true}});this.generQRCode=new k;new r};return t},{requires:["tc/mods/promotions/vir-ui","tc/mods/point/ui","tc/mods/winPoints/showWinPoint-ui","tc/mods/winPoints/winPoint-ui","tc/mods/authentication/ui",
"tc/mods/warning-popup/ui","tc/mods/itemInfo/ui","tc/mods/quantity/normal-ui","tc/mods/generQRCode/ui","tc/mods/memo/ui","tc/mods/payForAnother/ui","tc/mods/realPay/ui","tc/mods/submit/ui","tc/mods/checkCode/ui","tc/mods/totalFee/ui","tc/mods/point/fullPointPay-ui","tc/mods/totalPointPay/ui"]});
